package com.example.escaperoom;

import com.example.escaperoom.model.Slot;
import com.example.escaperoom.model.SlotStatus;
import com.example.escaperoom.repo.SlotRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class EscapeRoomApplication {

    public static void main(String[] args) {
        SpringApplication.run(EscapeRoomApplication.class, args);
    }

    /**
     * Seed a few slots for demo/testing.
     * In a real system, slots would likely be generated by a schedule service.
     */
    @Bean
    CommandLineRunner seedSlots(SlotRepository repo) {
        return args -> {
            // idempotent seeding
            repo.findById(1L).orElseGet(() -> repo.save(new Slot(1L, SlotStatus.AVAILABLE)));
            repo.findById(2L).orElseGet(() -> repo.save(new Slot(2L, SlotStatus.AVAILABLE)));
            repo.findById(3L).orElseGet(() -> repo.save(new Slot(3L, SlotStatus.AVAILABLE)));
        };
    }
}
