-- Pre-populate SLOTS for tests (matches schema.sql column names).

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT)
VALUES (1, 'AVAILABLE', NULL, NULL);

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT)
VALUES (2, 'AVAILABLE', NULL, NULL);

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT)
VALUES (3, 'AVAILABLE', NULL, NULL);
