-- Pre-populate SLOTS for tests (matches schema.sql column names).

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT, VERSION)
VALUES (1, 'AVAILABLE', NULL, NULL, 0);

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT, VERSION)
VALUES (2, 'AVAILABLE', NULL, NULL, 0);

INSERT INTO SLOTS (SLOT_ID, STATUS, HOLD_ID, HOLD_EXPIRES_AT, VERSION)
VALUES (3, 'AVAILABLE', NULL, NULL, 0);
